### ISSUE TITLE
Deploy cryptsetup-reencrypt in Heads to permit QubesOS image deployment in organization

### ISSUE THREAD

**Issue by tlaurion** [osresearch/heads#463]
Technical specifics discussion [here](https://github.com/QubesOS/qubes-issues/issues/1906#issuecomment-422142622) and [here](https://github.com/SkypLabs/my-qubes-os-formula/issues/6#issue-364582625) for rationale discussion which led to this.

Resumé:
QubesOS, Heads and Purism tried to collaborate to easily deploy QubesOS on trustworthy hardware. To do so, Purism and QubesOS created an OEM install disk that delayed OS installation after the user encrypted his disk.

The approach didn't take off, and from what I understand, that OEM install approach got dropped. @marmarek suggested that cryptsetup-reencrypt could be used but that approach was not really considered. Heads could reencrypt OEM/organization's installation offline. I'm testing that approach.

@kakaroto @kylerankin : Could you document what didn't take off with the [OEM disk approach](https://github.com/marmarek/qubes-installer-qubes-os/tree/r3.2-librem)?

**Comment by tlaurion** [comment]
To make cryptsetup-reencrypt available in heads:
```
diff --git a/modules/cryptsetup b/modules/cryptsetup
index e81d356..4cea7f3 100644
--- a/modules/cryptsetup
+++ b/modules/cryptsetup
@@ -15,6 +15,7 @@ cryptsetup_configure := ./configure \
 	--host i386-elf-linux \
 	--prefix "/" \
 	--disable-gcrypt-pbkdf2 \
+	--enable-cryptsetup-reencrypt \
 	--with-crypto_backend=kernel \
 
 # but after building, replace prefix so that they will be installed
@@ -28,6 +29,7 @@ cryptsetup_target := \
 
 cryptsetup_output := \
 	src/.libs/cryptsetup \
+	src/.libs/cryptsetup-reencrypt \
 	src/.libs/veritysetup \
 
 cryptsetup_libraries := \

```

**Comment by tlaurion** [comment]
Reencrypting after wiping out slot 1 used by TPMTOTP released key.
Estimated reencrytion time is 30 minutes on Intel SSD without any optimized settings, average speed is 80MiB/s.

**Comment by tlaurion** [comment]
Slows down to average 54MiB/s after a while and cruises there. Might need to tweak reencrypt settings with something like `[cryptsetup-reencrypt -B 32 --use-directio /dev/sda2](https://asalor.blogspot.com/2012/08/re-encryption-of-luks-device-cryptsetup.html)`.

**Comment by tlaurion** [comment]
Result report:

`cryptsetup-reencrypt /dev/sda2`: reencryption took 56m to reencrypt 151600MiB at an everage speed of 45.4 MiB/s
`cryptsetup-reencrypt -B 32 --use-directio /dev/sda2` : reencryption took 25m to reencrypt 151600 MiB at an average speed of 98.3 MiB/s

**Comment by tlaurion** [comment]
[From @kylerankin](https://github.com/osresearch/heads/pull/464#issuecomment-429913562): 
> I'd love to have an OEM-ready Qubes installer. The challenge with Qubes OEM images in the past was having resources with the expertise to build it. The Qubes team could do it but you would need to be willing to set up a consulting agreement with them and fund the effort.

**Comment by osresearch** [comment]
Was this resolved by merging #464 or is there more to be done?

**Comment by tlaurion** [comment]
https://github.com/osresearch/heads/issues/475 a whiptail menu permitting to reencrypt drive is still missing.

**Comment by tlaurion** [comment]
Included in #511

**Comment by tlaurion** [comment]
fixed in #551
