### ISSUE TITLE
Coreboot crossgcc is not verified

### ISSUE THREAD

**Issue by osresearch** [osresearch/heads#9]
The Coreboot crossgcc target is not verified and does not check certs.  In `util/crossgcc/buildgcc`:

```
download_showing_percentage() {
        url=$1
        printf " ..${red}  0%%"
        wget --no-check-certificate $url 2>&1 | while read line; do
                printf "${red}"
                echo $line | grep -o "[0-9]\+%" | awk '{printf("\b\b\b\b%4s", $1)}'
                printf "${NC}"
        done
}
```

**Comment by osresearch** [comment]
Looks like this is currently pending review: https://review.coreboot.org/#/c/15170/

**Comment by zaolin** [comment]
I am on it. The next 4 weeks I have time do that in my holidays ;)

**Comment by zaolin** [comment]
Should be done. I pushed some updates. Should get merged in some days..

**Comment by osresearch** [comment]
Any update on your patches?  It looks like the current `coreboot/util/crossgcc/buildgcc` still doesn't validate any hashes after downloading: https://github.com/coreboot/coreboot/blob/2c6a8060da994bb22eb1619d55ee74be096682b5/util/crossgcc/buildgcc#L300

**Comment by zaolin** [comment]
I am on it. Took longer than expected. Hopefully it gets merged this week.

**Comment by merge** [comment]
It seem like [this commit](https://github.com/coreboot/coreboot/commit/92d483a8927066ef16603023be05ad1fb7dea644) implemented this.
